#!/bin/sh

# A sample post-deploy hook
#
# These environment variables are available:
# KAMAL_RECORDED_AT
# KAMAL_PERFORMER
# KAMAL_VERSION
# KAMAL_HOSTS
# KAMAL_ROLES (if set)
# KAMAL_DESTINATION (if set)
# KAMAL_RUNTIME

API_KEY=$(RAILS_ENV=production bundle exec rails runner "print Rails.application.credentials.dig(:honeybadger, :api_key)")

bundle exec honeybadger deploy \
  --api-key "$API_KEY" \
  --repository https://github.com/roasted-oolong/hawk \
  --revision $KAMAL_VERSION \
  --environment production \
  --user $KAMAL_PERFORMER
  
echo "$KAMAL_PERFORMER deployed $KAMAL_VERSION to $KAMAL_DESTINATION in $KAMAL_RUNTIME seconds"
