// modal_controller.ts
//
// Confirmation modal using the native HTML <dialog> element.
//
// Replaces data-turbo-confirm on all destructive actions. Each trigger
// (a button_to or link_to wrapper) mounts this controller, which opens
// the shared #modal-dialog and registers itself so the dialog's own
// controller can call back on confirm/cancel.
//
// Usage — wrap the button_to in a controller div:
//
//   <div data-controller="modal"
//        data-modal-message-value="Remove 'Foo'? This cannot be undone."
//        data-modal-confirm-label-value="Remove"
//        data-modal-danger-value="true">
//     <%= button_to "Remove", ..., data: { action: "modal#open" } %>
//   </div>
//
// Layout requirement: one shared <dialog id="modal-dialog"> in the layout,
// with data-controller="dialog" (see dialog_controller.ts).

import { Controller } from "@hotwired/stimulus"

export default class ModalController extends Controller {
  static values = {
    message:      { type: String,  default: "Are you sure?" },
    confirmLabel: { type: String,  default: "Confirm" },
    danger:       { type: Boolean, default: true },
  }

  declare messageValue:      string
  declare confirmLabelValue: string
  declare dangerValue:       boolean

  // The form generated by button_to that we will submit on confirm.
  private pendingForm: HTMLFormElement | null = null

  open(event: Event): void {
    event.preventDefault()

    // The button_to generates a <form> as immediate parent of the button.
    // Our controller element wraps that form.
    this.pendingForm = (event.currentTarget as HTMLElement).closest("form")

    const dialog = document.getElementById("modal-dialog") as HTMLDialogElement & {
      _modalController?: ModalController
    }
    dialog._modalController = this

    const messageEl  = dialog.querySelector("[data-modal-message]")  as HTMLElement
    const confirmBtn = dialog.querySelector("[data-modal-confirm]")   as HTMLButtonElement

    messageEl.textContent   = this.messageValue
    confirmBtn.textContent  = this.confirmLabelValue
    confirmBtn.className    = this.dangerValue ? "btn btn--danger" : "btn btn--primary"

    dialog.showModal()
  }

  // Called by DialogController on confirm.
  handleConfirm(): void {
    if (this.pendingForm) {
      this.pendingForm.requestSubmit()
    }
    this.pendingForm = null
  }

  // Called by DialogController on cancel.
  handleCancel(): void {
    this.pendingForm = null
  }

  disconnect(): void {
    this.pendingForm = null
  }
}
