require "rails_helper"

# Fixtures under spec/fixtures/formatter/ were generated by invoking the real
# Python functions (src/formatter/prompt_builder.py) directly and saving
# their output — not hand-transcribed — so these assert genuine byte-for-byte
# parity per docs/RAILS_REFACTOR_PLAN.md's R6.5 acceptance criterion.
RSpec.describe Pipeline::Ruby::FormatterPromptBuilder do
  def fixture(name)
    File.read(Rails.root.join("spec/fixtures/formatter", name), encoding: "UTF-8")
  end

  describe ".build_system_prompt" do
    it "byte-matches Python's build_system_prompt output" do
      expect(described_class.build_system_prompt).to eq(fixture("system_prompt.txt"))
    end
  end

  describe ".build_user_message" do
    it "byte-matches Python's build_user_message output for a multi-chapter batch" do
      chapters = {
        2 => "  Second chapter text with leading/trailing space.  ",
        1 => "First chapter text.\nSecond line."
      }

      expect(described_class.build_user_message(chapters)).to eq(fixture("user_message_sample.txt"))
    end

    it "orders chapters numerically regardless of hash insertion order" do
      message = described_class.build_user_message({ 3 => "third", 1 => "first" })

      expect(message.index("=== CHAPTER 1 ===")).to be < message.index("=== CHAPTER 3 ===")
    end
  end
end
