require "rails_helper"

# Fixtures under spec/fixtures/voice_calibration/ were generated by invoking
# the real Python functions (src/voice_calibration/prompt_builder.py)
# directly and saving their output — not hand-transcribed.
RSpec.describe Pipeline::Ruby::VoiceCalibration::PromptBuilder do
  def fixture(name)
    File.read(Rails.root.join("spec/fixtures/voice_calibration", name), encoding: "UTF-8")
  end

  describe ".build_system_prompt" do
    it "byte-matches Python's build_system_prompt output (no arguments, static text)" do
      expect(described_class.build_system_prompt).to eq(fixture("system_prompt.txt"))
    end
  end

  describe ".build_user_message" do
    it "byte-matches Python's build_user_message output for the same context" do
      context = described_class::ReviewContext.new(
        voice_calibration:  "## Passage 1 — Existing pattern\n\n> An existing quote.\n\n**The rule it demonstrates:** An existing rule.",
        translated_chapter: "The rain fell steadily over Seoul as Min-jun walked home.\nHe thought about the audition.\n",
        chapter_num:        5
      )

      expect(described_class.build_user_message(context)).to eq(fixture("user_message_sample.txt"))
    end

    it "omits the Voice Calibration section when empty, same as Python's section() filter" do
      context = described_class::ReviewContext.new(
        voice_calibration: "", translated_chapter: "text", chapter_num: 1
      )

      message = described_class.build_user_message(context)
      expect(message).not_to include("Voice Calibration")
      expect(message).to include("# Chapter 1 — Translated Text")
    end
  end
end
