require "rails_helper"

# Fixtures under spec/fixtures/preread/ were originally generated by invoking
# the real Python functions (src/preread/prompt_builder.py) directly and
# saving their output — not hand-transcribed — so these assert genuine
# byte-for-byte parity per docs/RAILS_REFACTOR_PLAN.md's R6 acceptance
# criterion, not just a plausible-looking approximation.
#
# Exception: system_prompt_2026-07-25.txt's CULTURAL PHRASES section was
# hand-edited 2026-08-08 to match PromptBuilder's deliberate departure from
# Python there (see that section's comment in prompt_builder.rb) — Python's
# own output no longer matches this one section, by design.
RSpec.describe Pipeline::Ruby::PrereadRunner::PromptBuilder do
  def fixture(name)
    File.read(Rails.root.join("spec/fixtures/preread", name), encoding: "UTF-8")
  end

  describe ".build_system_prompt" do
    it "byte-matches Python's build_system_prompt output for the same date, except the deliberately-diverged CULTURAL PHRASES section" do
      expect(described_class.build_system_prompt("2026-07-25"))
        .to eq(fixture("system_prompt_2026-07-25.txt"))
    end
  end

  describe ".build_user_message" do
    it "byte-matches Python's build_user_message output for the same context" do
      context = described_class::PrereadContext.new(
        novel_info: "Genre: romance fantasy\nSetting: modern Seoul idol industry",
        characters: "## Hee-yeon Lee (이희연) — English\n- Role: protagonist",
        cultural_phrases: "",
        locations: "[Location Name — English]\n- Korean name: ",
        story: "## Open Arcs\n- Debut arc in motion",
        terminology: "## Debut — English\n- Definition: first public performance",
        chapters: { 2 => " Chapter two text.  ", 1 => "Chapter one text." },
        today: "2026-07-25"
      )

      expect(described_class.build_user_message(context)).to eq(fixture("user_message_sample.txt"))
    end

    it "omits reference sections that are empty or template-only, same as Python's section() filter" do
      context = described_class::PrereadContext.new(
        novel_info: "", characters: "", cultural_phrases: "", locations: "",
        story: "", terminology: "", chapters: { 1 => "text" }, today: "2026-07-25"
      )

      message = described_class.build_user_message(context)
      expect(message).not_to include("Current Characters Bible")
      expect(message).to include("=== CHAPTER 1 ===")
    end
  end
end
