require "rails_helper"
require "json"

# system_prompt_sample.txt was generated by invoking the real Python
# build_translation_prompt directly and saving its output, then hand-
# stripping the one deliberate difference (the web_search-instructing
# sentence — see the class comment) — not hand-transcribed, so this asserts
# genuine byte-for-byte parity per docs/RAILS_REFACTOR_PLAN.md's R4
# acceptance criterion, modulo that one named difference.
RSpec.describe Pipeline::Ruby::TranslateBatch::PromptBuilder do
  def fixture(name)
    File.read(Rails.root.join("spec/fixtures/translate_batch", name), encoding: "UTF-8")
  end

  describe ".build_system_prompt" do
    it "byte-matches Python's build_translation_prompt output, minus the deliberately stripped web_search sentence" do
      context = described_class::TranslationContext.new(
        novel_info: "Genre: romance fantasy\nSetting: modern Seoul idol industry",
        translation_guidelines: "Phase 1: literal pass. Phase 2: polish for readability.",
        narrator_note: "Kang narrates in first person, dry and self-deprecating.",
        characters: "## Hyuk Kang — English\n- Role: protagonist",
        cultural_phrases: "[Phrase — English or descriptive label]\n- Korean phrase: ",
        locations: "## K Management — English\n- Significance: protagonist's new agency",
        story: "",
        terminology: "## Comeback — English\n- Definition: a group's return with new material",
        voice_calibration: "## Passage 1 — Dry deflection\n> quote here"
      )

      expect(described_class.build_system_prompt(context)).to eq(fixture("system_prompt_sample.txt"))
    end

    it "never emits the web_search sentence — R3's bridge doesn't wire that tool" do
      context = described_class::TranslationContext.new(
        novel_info: "info", translation_guidelines: "", narrator_note: "",
        characters: "", cultural_phrases: "", locations: "", story: "",
        terminology: "", voice_calibration: ""
      )

      expect(described_class.build_system_prompt(context)).not_to include("web_search")
    end

    it "omits reference sections that are empty or template-only, same as Python's section() filter" do
      context = described_class::TranslationContext.new(
        novel_info: "", translation_guidelines: "", narrator_note: "",
        characters: "", cultural_phrases: "", locations: "", story: "",
        terminology: "", voice_calibration: ""
      )

      message = described_class.build_system_prompt(context)
      expect(message).not_to include("Character Bible")
      expect(message).not_to include("Narrator Note")
    end
  end

  describe ".build_feel_check_system_prompt" do
    it "is Korean-blind, same as build_editor_system_prompt" do
      prompt = described_class.build_feel_check_system_prompt

      expect(prompt.downcase).to include("do not have access to the korean source")
    end

    it "asks for a rewrite, not just a flag, on a segment that doesn't read naturally" do
      prompt = described_class.build_feel_check_system_prompt

      expect(prompt).to include('"reads_naturally"')
      expect(prompt).to include('"rewritten_text"')
    end

    it "instructs the model to return a single JSON object with a segments array" do
      prompt = described_class.build_feel_check_system_prompt

      expect(prompt).to include('"segments"')
      expect(prompt).to include('"segment_id"')
    end
  end

  describe ".build_feel_check_user_message" do
    it "renders the given segments as JSON under a Segments heading" do
      segments = [ { "segment_id" => 1, "text" => "Some English text." } ]

      message = described_class.build_feel_check_user_message(segments: segments)

      expect(message).to include("# Segments")
      expect(message).to include('"segment_id": 1')
      expect(message).to include("Some English text.")
    end
  end

  describe ".build_title_finalize_system_prompt" do
    it "scopes the call to the title only, informed by the finished body" do
      prompt = described_class.build_title_finalize_system_prompt

      expect(prompt).to include("translate this chapter's title, and only its title")
      expect(prompt.downcase).to include("finished english body")
    end
  end

  describe ".build_title_finalize_user_message" do
    it "gives the Korean title, the draft title, and the finished English body under distinct headings" do
      message = described_class.build_title_finalize_user_message(
        korean_title: "한국어 제목",
        draft_title:  "Draft Title",
        english_body: "The finished English body text."
      )

      expect(message).to include("# Korean Title")
      expect(message).to include("한국어 제목")
      expect(message).to include("# Draft Title")
      expect(message).to include("Draft Title")
      expect(message).to include("# Finished English Chapter Body")
      expect(message).to include("The finished English body text.")
    end
  end

  describe ".build_beat_classification_system_prompt" do
    def context(overrides = {})
      described_class::TranslationContext.new(
        **{
          novel_info: "Genre: romance fantasy", translation_guidelines: "Be faithful.",
          narrator_note: "Kang narrates dryly.", characters: "## Hyuk Kang\n- Role: protagonist",
          cultural_phrases: "", locations: "", story: "", terminology: "", voice_calibration: ""
        }.merge(overrides)
      )
    end

    it "instructs the model to return a single JSON object with a blocks array" do
      prompt = described_class.build_beat_classification_system_prompt(context)

      expect(prompt).to include('"blocks"')
      expect(prompt).to include("Respond with a single JSON object")
    end

    it "specifies block_id, speaker, and label as the per-block fields" do
      prompt = described_class.build_beat_classification_system_prompt(context)

      expect(prompt).to include('"block_id"')
      expect(prompt).to include('"speaker"')
      expect(prompt).to include('"label"')
    end

    it "defines the CONTINUE/BREAK/BRIDGE labels" do
      prompt = described_class.build_beat_classification_system_prompt(context)

      expect(prompt).to include("CONTINUE")
      expect(prompt).to include("BREAK")
      expect(prompt).to include("BRIDGE")
    end

    it "states the chapter is already pre-chunked and scene breaks are already handled" do
      prompt = described_class.build_beat_classification_system_prompt(context)

      expect(prompt).to include("already been mechanically split")
      expect(prompt).to include("scene break")
    end

    it "defines a beat as potentially spanning multiple speakers, not just one speaker's turn" do
      prompt = described_class.build_beat_classification_system_prompt(context)

      expect(prompt).to include("back-and-forth exchange between two speakers can be one beat")
    end

    it "does not instruct translation or analysis — this call is classification only" do
      prompt = described_class.build_beat_classification_system_prompt(context)

      expect(prompt).not_to include("localized_translation")
      expect(prompt).not_to include("core_message")
    end

    it "never emits the web_search sentence" do
      expect(described_class.build_beat_classification_system_prompt(context)).not_to include("web_search")
    end

    it "includes the shared reference material" do
      prompt = described_class.build_beat_classification_system_prompt(context)

      expect(prompt).to include("Genre: romance fantasy")
      expect(prompt).to include("Hyuk Kang")
      expect(prompt).to include("Character Bible")
    end

    it "omits reference sections that are empty or template-only" do
      prompt = described_class.build_beat_classification_system_prompt(context(characters: "", novel_info: ""))

      expect(prompt).not_to include("Character Bible")
    end
  end

  describe ".build_beat_classification_user_message" do
    def block(id, text, scene_break: false)
      Pipeline::Ruby::TranslateBatch::BeatSegmenter::CandidateBlock.new(block_id: id, text: text, scene_break: scene_break)
    end

    it "renders non-scene-break blocks grouped under a scene heading with their block_id" do
      message = described_class.build_beat_classification_user_message(candidate_blocks: [ block(1, "안녕") ])

      expect(message).to include("# Scene 1")
      expect(message).to include("[Block 1]")
      expect(message).to include("안녕")
    end

    it "renders a scene_break block as a (scene break) marker and starts a new scene heading after it" do
      candidate_blocks = [ block(1, "text one"), block(2, "***", scene_break: true), block(3, "text two") ]

      message = described_class.build_beat_classification_user_message(candidate_blocks: candidate_blocks)

      expect(message).to include("# Scene 1")
      expect(message).to include("(scene break)")
      expect(message).to include("# Scene 2")
      expect(message.index("# Scene 1")).to be < message.index("(scene break)")
      expect(message.index("(scene break)")).to be < message.index("# Scene 2")
    end
  end

  describe ".build_analysis_system_prompt" do
    def context(overrides = {})
      described_class::TranslationContext.new(
        **{
          novel_info: "Genre: romance fantasy", translation_guidelines: "Be faithful.",
          narrator_note: "Kang narrates dryly.", characters: "## Hyuk Kang\n- Role: protagonist",
          cultural_phrases: "", locations: "", story: "", terminology: "", voice_calibration: ""
        }.merge(overrides)
      )
    end

    it "instructs the model to return a single JSON object with a passages array" do
      prompt = described_class.build_analysis_system_prompt(context)

      expect(prompt).to include('"passages"')
      expect(prompt).to include("Respond with a single JSON object")
    end

    it "specifies passage_id as the join key back to segmentation, not anchor_quote matching" do
      prompt = described_class.build_analysis_system_prompt(context)

      expect(prompt).to include('"passage_id"')
      expect(prompt).to include("join key")
    end

    it "includes the five literary-analysis fields" do
      prompt = described_class.build_analysis_system_prompt(context)

      expect(prompt).to include('"core_message"')
      expect(prompt).to include('"emphasis"')
      expect(prompt).to include('"pacing_rhythm"')
      expect(prompt).to include('"voice_register"')
      expect(prompt).to include('"narrative_function"')
    end

    it "retains cultural_signals, localization_strategy, and bible_entries_used" do
      prompt = described_class.build_analysis_system_prompt(context)

      expect(prompt).to include('"cultural_signals"')
      expect(prompt).to include('"localization_strategy"')
      expect(prompt).to include('"bible_entries_used"')
    end

    it "constrains localization_strategy.category to the controlled six-value taxonomy plus none" do
      prompt = described_class.build_analysis_system_prompt(context)

      %w[behavioral idiomatic tone_shift register_shift motif_reinterpretation demographic_voice none].each do |value|
        expect(prompt).to include(value)
      end
    end

    it "scopes bible_entries_used to attribution only, not a content dump" do
      prompt = described_class.build_analysis_system_prompt(context)

      expect(prompt).to include("bible_lookup")
    end

    it "forbids producing any English rendering of the passage's content" do
      prompt = described_class.build_analysis_system_prompt(context)

      expect(prompt).to include("Do not write any English translation, paraphrase, or rendering")
      expect(prompt).not_to include("localized_translation")
    end

    it "never emits the web_search sentence" do
      expect(described_class.build_analysis_system_prompt(context)).not_to include("web_search")
    end

    it "includes the shared reference material" do
      prompt = described_class.build_analysis_system_prompt(context)

      expect(prompt).to include("Genre: romance fantasy")
      expect(prompt).to include("Hyuk Kang")
      expect(prompt).to include("Character Bible")
    end

    it "omits reference sections that are empty or template-only" do
      prompt = described_class.build_analysis_system_prompt(context(characters: "", novel_info: ""))

      expect(prompt).not_to include("Character Bible")
    end

    it "injects cultural_patterns content into its own section, separate from the shared reference material" do
      prompt = described_class.build_analysis_system_prompt(context, cultural_patterns: "Status-jockeying (기 싸움) notes here")

      expect(prompt).to include("## Cultural Patterns")
      expect(prompt).to include("Status-jockeying (기 싸움) notes here")
    end

    it "omits the Cultural Patterns section heading when no cultural_patterns content is given" do
      prompt = described_class.build_analysis_system_prompt(context)

      expect(prompt).not_to include("## Cultural Patterns")
    end

    it "never leaks cultural_patterns content into the single-pass prompt" do
      described_class.build_analysis_system_prompt(context, cultural_patterns: "some pattern notes")
      single_pass = described_class.build_system_prompt(context)

      expect(single_pass).not_to include("some pattern notes")
    end
  end

  describe ".build_analysis_user_message" do
    it "includes the segmentation result JSON under its own heading" do
      segmentation = { "passages" => [ { "passage_id" => 1, "speakers" => [ "narration" ], "anchor_quote" => "챕터 1" } ] }

      message = described_class.build_analysis_user_message(segmentation_result: segmentation)

      expect(message).to include("# Segmented Passages")
      parsed_back = JSON.parse(message[/\{.*\}/m])
      expect(parsed_back).to eq(segmentation)
    end
  end

  describe ".build_localization_system_prompt" do
    def context(overrides = {})
      described_class::TranslationContext.new(
        **{
          novel_info: "Genre: romance fantasy", translation_guidelines: "Be faithful.",
          narrator_note: "Kang narrates dryly.", characters: "## Hyuk Kang\n- Role: protagonist",
          cultural_phrases: "", locations: "", story: "", terminology: "", voice_calibration: ""
        }.merge(overrides)
      )
    end

    it "instructs the model to return a single JSON object with a localized_passages array" do
      prompt = described_class.build_localization_system_prompt(context)

      expect(prompt).to include('"localized_passages"')
      expect(prompt).to include("Respond with a single JSON object")
    end

    it "echoes passage_id as the join key, not anchor_quote matching" do
      prompt = described_class.build_localization_system_prompt(context)

      expect(prompt).to include('"passage_id"')
      expect(prompt).to include("echo the given")
    end

    it "instructs executing localization_strategy, not just detecting it" do
      prompt = described_class.build_localization_system_prompt(context)

      expect(prompt).to include("localization_strategy")
      expect(prompt).to include("concrete")
    end

    it "instructs rewriting as continuous prose rather than sentence-by-sentence substitution" do
      prompt = described_class.build_localization_system_prompt(context)

      expect(prompt).to include("not a sentence-by-sentence substitution")
      expect(prompt).to include("merge, split, or reorder clauses")
    end

    it "warns against mixing idiom registers within a single speaker's own lines" do
      prompt = described_class.build_localization_system_prompt(context)

      expect(prompt).to include("do not mix idiom registers within a single speaker's own lines")
    end

    it "allows multi-speaker passages but still requires them to read as one connected beat" do
      prompt = described_class.build_localization_system_prompt(context)

      expect(prompt).to include("speakers")
      expect(prompt).to include("read as one connected beat")
    end

    it "instructs localized_passages to concatenate into the complete chapter with no commentary" do
      prompt = described_class.build_localization_system_prompt(context)

      expect(prompt.downcase).to include("concatenat")
      expect(prompt).to include("no commentary")
    end

    it "does not include any self-graded editorial_checks block — self-grading was removed from this design" do
      prompt = described_class.build_localization_system_prompt(context)

      expect(prompt).not_to include("editorial_checks")
      expect(prompt).to include("it does not grade itself")
    end

    it "never emits the web_search sentence" do
      expect(described_class.build_localization_system_prompt(context)).not_to include("web_search")
    end

    it "includes the shared reference material" do
      prompt = described_class.build_localization_system_prompt(context)

      expect(prompt).to include("Genre: romance fantasy")
      expect(prompt).to include("Hyuk Kang")
      expect(prompt).to include("Character Bible")
    end

    it "omits reference sections that are empty or template-only" do
      prompt = described_class.build_localization_system_prompt(context(characters: "", novel_info: ""))

      expect(prompt).not_to include("Character Bible")
    end

    it "injects cultural_patterns content into its own section, separate from the shared reference material" do
      prompt = described_class.build_localization_system_prompt(context, cultural_patterns: "Status-jockeying (기 싸움) notes here")

      expect(prompt).to include("## Cultural Patterns")
      expect(prompt).to include("Status-jockeying (기 싸움) notes here")
    end

    it "omits the Cultural Patterns section heading when no cultural_patterns content is given" do
      prompt = described_class.build_localization_system_prompt(context)

      expect(prompt).not_to include("## Cultural Patterns")
    end

    it "never leaks cultural_patterns content into the single-pass prompt" do
      described_class.build_localization_system_prompt(context, cultural_patterns: "some pattern notes")
      single_pass = described_class.build_system_prompt(context)

      expect(single_pass).not_to include("some pattern notes")
    end
  end

  describe ".build_localization_user_message" do
    it "includes the segmentation and analysis JSON under distinct headings" do
      segmentation = { "passages" => [ { "passage_id" => 1, "anchor_quote" => "챕터 1" } ] }
      analysis = { "passages" => [ { "passage_id" => 1, "core_message" => "opens the chapter" } ] }

      message = described_class.build_localization_user_message(segmentation_result: segmentation, analysis_result: analysis)

      expect(message).to include("# Segmented Passages (Korean)")
      expect(message).to include("# Literary Analysis")
      expect(message).to include("챕터 1")
      expect(message).to include("opens the chapter")
    end
  end

  describe ".build_factcheck_system_prompt" do
    def context(overrides = {})
      described_class::TranslationContext.new(
        **{
          novel_info: "Genre: romance fantasy", translation_guidelines: "Be faithful.",
          narrator_note: "Kang narrates dryly.", characters: "## Hyuk Kang\n- Role: protagonist",
          cultural_phrases: "", locations: "", story: "", terminology: "", voice_calibration: ""
        }.merge(overrides)
      )
    end

    it "tells the reviewer it did not write the translation" do
      prompt = described_class.build_factcheck_system_prompt(context)

      expect(prompt).to include("You did not write the translation")
    end

    it "instructs the model to return a single JSON object with a reviewed_passages array" do
      prompt = described_class.build_factcheck_system_prompt(context)

      expect(prompt).to include('"reviewed_passages"')
      expect(prompt).to include("Respond with a single JSON object")
    end

    it "asks for five fact/culture/compliance checks, not prose-quality checks" do
      prompt = described_class.build_factcheck_system_prompt(context)

      expect(prompt).to include("names_preserved")
      expect(prompt).to include("facts_preserved")
      expect(prompt).to include("cultural_significance_preserved")
      expect(prompt).to include("cultural_dynamic_enacted")
      expect(prompt).to include("style_guidelines_followed")
      expect(prompt).not_to include("continuous_utterance")
      expect(prompt).not_to include("register_unified")
    end

    it "anchors names_preserved to the bible's established spelling, not just Korean fidelity" do
      prompt = described_class.build_factcheck_system_prompt(context)

      expect(prompt).to include("Character Bible / Locations / Terminology sections")
      expect(prompt).to include("bible_lookup")
    end

    it "scopes style_guidelines_followed to stated rules like tense, distinct from prose quality" do
      prompt = described_class.build_factcheck_system_prompt(context)

      expect(prompt).to include("style_guidelines_followed")
      expect(prompt).to include("narration tense")
    end

    it "explicitly scopes out prose-quality judgment to a separate call" do
      prompt = described_class.build_factcheck_system_prompt(context)

      expect(prompt).to include("not judging prose quality")
    end

    it "requires flagging when the analysis named something important missing from the translation" do
      prompt = described_class.build_factcheck_system_prompt(context)

      expect(prompt).to include("compare the passage's analysis to its English translation directly")
    end

    it "requires a quoted finding for any false check, not a bare boolean" do
      prompt = described_class.build_factcheck_system_prompt(context)

      expect(prompt).to include("must have at least one corresponding entry in `findings`")
      expect(prompt).to include("quoting the exact substring")
    end

    it "never emits the web_search sentence" do
      expect(described_class.build_factcheck_system_prompt(context)).not_to include("web_search")
    end

    it "includes the shared reference material" do
      prompt = described_class.build_factcheck_system_prompt(context)

      expect(prompt).to include("Genre: romance fantasy")
      expect(prompt).to include("Hyuk Kang")
      expect(prompt).to include("Character Bible")
    end

    it "injects cultural_patterns content into its own section" do
      prompt = described_class.build_factcheck_system_prompt(context, cultural_patterns: "Status-jockeying (기 싸움) notes here")

      expect(prompt).to include("## Cultural Patterns")
      expect(prompt).to include("Status-jockeying (기 싸움) notes here")
    end

    it "never leaks cultural_patterns content into the single-pass prompt" do
      described_class.build_factcheck_system_prompt(context, cultural_patterns: "some pattern notes")
      single_pass = described_class.build_system_prompt(context)

      expect(single_pass).not_to include("some pattern notes")
    end
  end

  describe ".build_factcheck_user_message" do
    it "includes segmentation, analysis, and localization JSON under distinct headings" do
      segmentation = { "passages" => [ { "passage_id" => 1, "anchor_quote" => "챕터 1" } ] }
      analysis = { "passages" => [ { "passage_id" => 1, "core_message" => "opens the chapter" } ] }
      localization = { "localized_passages" => [ { "passage_id" => 1, "localized_translation" => "Chapter one." } ] }

      message = described_class.build_factcheck_user_message(
        segmentation_result: segmentation, analysis_result: analysis, localization_result: localization
      )

      expect(message).to include("# Segmented Passages (Korean)")
      expect(message).to include("# Literary Analysis")
      expect(message).to include("# English Translation")
      expect(message).to include("Chapter one.")
    end
  end

  describe ".build_editor_system_prompt" do
    it "tells the reviewer it has no access to the Korean source or analysis" do
      prompt = described_class.build_editor_system_prompt

      expect(prompt).to include("You do not have access to the Korean source or to any analysis of it")
    end

    it "instructs the model to return a single JSON object with a reviewed_passages array" do
      prompt = described_class.build_editor_system_prompt

      expect(prompt).to include('"reviewed_passages"')
      expect(prompt).to include("Respond with a single JSON object")
    end

    it "asks for four prose-quality checks, not fact/culture checks" do
      prompt = described_class.build_editor_system_prompt

      expect(prompt).to include("continuous_utterance")
      expect(prompt).to include("register_unified")
      expect(prompt).to include("narrative_flow")
      expect(prompt).to include("natural_english")
      expect(prompt).not_to include("names_preserved")
      expect(prompt).not_to include("facts_preserved")
    end

    it "requires a quoted finding for any false check, not a bare boolean" do
      prompt = described_class.build_editor_system_prompt

      expect(prompt).to include("must have at least one corresponding entry in `findings`")
      expect(prompt).to include("quoting the exact substring")
    end

    it "never emits the web_search sentence" do
      expect(described_class.build_editor_system_prompt).not_to include("web_search")
    end

    it "takes no context/reference-material arguments — it must stay blind to the Korean and any bible/style reference" do
      expect(described_class.method(:build_editor_system_prompt).arity).to eq(0)
    end
  end

  describe ".build_editor_user_message" do
    it "includes only the localization result, with no Korean or analysis content" do
      localization = { "localized_passages" => [ { "passage_id" => 1, "localized_translation" => "Chapter one." } ] }

      message = described_class.build_editor_user_message(localization_result: localization)

      expect(message).to include("# Translated Passages")
      expect(message).to include("Chapter one.")
    end
  end

  describe ".build_chapter_qa_factcheck_system_prompt" do
    def context(overrides = {})
      described_class::TranslationContext.new(
        **{
          novel_info: "Genre: romance fantasy", translation_guidelines: "Be faithful.",
          narrator_note: "Kang narrates dryly.", characters: "## Hyuk Kang\n- Role: protagonist",
          cultural_phrases: "", locations: "", story: "", terminology: "", voice_calibration: ""
        }.merge(overrides)
      )
    end

    it "tells the reviewer it did not write the translation" do
      prompt = described_class.build_chapter_qa_factcheck_system_prompt(context)

      expect(prompt).to include("You did not write the translation")
    end

    it "instructs the model to return a single JSON object with a flat suggestions array, not reviewed_passages" do
      prompt = described_class.build_chapter_qa_factcheck_system_prompt(context)

      expect(prompt).to include('"suggestions"')
      expect(prompt).not_to include("reviewed_passages")
      expect(prompt).not_to include("passage_id")
      expect(prompt).to include("Respond with a single JSON object")
    end

    it "requires a concrete suggested_revision and a structured severity, not just an issue description" do
      prompt = described_class.build_chapter_qa_factcheck_system_prompt(context)

      expect(prompt).to include("suggested_revision")
      expect(prompt).to include("always give a concrete rewrite")
      expect(prompt).to include('"strong" or "advisory"')
    end

    it "asks for korean_context on every finding" do
      prompt = described_class.build_chapter_qa_factcheck_system_prompt(context)

      expect(prompt).to include("korean_context")
    end

    it "explicitly scopes out prose-quality judgment to a separate call" do
      prompt = described_class.build_chapter_qa_factcheck_system_prompt(context)

      expect(prompt).to include("not judging prose quality")
    end

    it "anchors name checks to the bible's established spelling, not just whether the Korean was lost" do
      prompt = described_class.build_chapter_qa_factcheck_system_prompt(context)

      expect(prompt).to include("Character Bible / Locations / Terminology sections")
      expect(prompt).to include("bible_lookup")
    end

    it "flags Translation Guidelines violations like narration tense, separately from prose quality" do
      prompt = described_class.build_chapter_qa_factcheck_system_prompt(context)

      expect(prompt).to include("Translation Guidelines section")
      expect(prompt).to include("narration tense")
    end

    it "includes the shared reference material" do
      prompt = described_class.build_chapter_qa_factcheck_system_prompt(context)

      expect(prompt).to include("Genre: romance fantasy")
      expect(prompt).to include("Hyuk Kang")
      expect(prompt).to include("Character Bible")
    end

    it "injects cultural_patterns content into its own section" do
      prompt = described_class.build_chapter_qa_factcheck_system_prompt(context, cultural_patterns: "Status-jockeying (기 싸움) notes here")

      expect(prompt).to include("## Cultural Patterns")
      expect(prompt).to include("Status-jockeying (기 싸움) notes here")
    end
  end

  describe ".build_chapter_qa_factcheck_user_message" do
    it "includes the whole Korean source and whole English translation under distinct headings" do
      message = described_class.build_chapter_qa_factcheck_user_message(
        korean_text: "챕터 1 한국어", english_text: "Chapter one, in English."
      )

      expect(message).to include("# Korean Source")
      expect(message).to include("챕터 1 한국어")
      expect(message).to include("# English Translation")
      expect(message).to include("Chapter one, in English.")
    end
  end

  describe ".build_chapter_qa_editor_system_prompt" do
    it "tells the reviewer it has no access to the Korean source" do
      prompt = described_class.build_chapter_qa_editor_system_prompt

      expect(prompt).to include("You do not have access to the Korean source")
    end

    it "instructs the model to return a single JSON object with a flat suggestions array, not reviewed_passages" do
      prompt = described_class.build_chapter_qa_editor_system_prompt

      expect(prompt).to include('"suggestions"')
      expect(prompt).not_to include("reviewed_passages")
      expect(prompt).not_to include("passage_id")
    end

    it "requires a concrete suggested_revision and a structured severity" do
      prompt = described_class.build_chapter_qa_editor_system_prompt

      expect(prompt).to include("suggested_revision")
      expect(prompt).to include('"strong" or "advisory"')
    end

    it "never asks for korean_context — it has no Korean to draw one from" do
      expect(described_class.build_chapter_qa_editor_system_prompt).not_to include("korean_context")
    end

    it "takes no context/reference-material arguments — it must stay blind to the Korean and any bible/style reference" do
      expect(described_class.method(:build_chapter_qa_editor_system_prompt).arity).to eq(0)
    end
  end

  describe ".build_chapter_qa_editor_user_message" do
    it "includes only the English translation, with no Korean content" do
      message = described_class.build_chapter_qa_editor_user_message(english_text: "Chapter one, in English.")

      expect(message).to include("# English Translation")
      expect(message).to include("Chapter one, in English.")
    end
  end

  describe ".extract_narrator_note" do
    it "extracts the Narrator Note section when followed by another section" do
      novel_info = "# Title\n\n## Narrator Note\nSome note text.\nMore text.\n\n## Next Section\nOther stuff"
      expect(described_class.extract_narrator_note(novel_info)).to eq("Some note text.\nMore text.")
    end

    it "extracts the Narrator Note section when it's the last section in the file" do
      novel_info = "# Title\n\n## Narrator Note\nSome note text.\n"
      expect(described_class.extract_narrator_note(novel_info)).to eq("Some note text.")
    end

    it "returns an empty string when there is no Narrator Note section" do
      expect(described_class.extract_narrator_note("# Title\n\n## Other Section\nstuff")).to eq("")
    end

    it "handles Korean content inside the note without an ASCII-only \\w gap" do
      novel_info = "## Narrator Note\n강혁 narrates dryly.\n\n## Next"
      expect(described_class.extract_narrator_note(novel_info)).to eq("강혁 narrates dryly.")
    end

    it "returns an empty string for nil input" do
      expect(described_class.extract_narrator_note(nil)).to eq("")
    end
  end

  describe ".load_reference_files" do
    it "reads all 8 NOVEL_FILES from the novel/bible directories, empty string for missing ones" do
      Dir.mktmpdir do |novel_dir|
        FileUtils.mkdir_p(File.join(novel_dir, "bible"))
        File.write(File.join(novel_dir, "novel_info.md"), "novel info content")
        File.write(File.join(novel_dir, "bible", "characters.md"), "characters content")
        # translation_guidelines.md, voice_calibration.md, cultural_phrases.md,
        # locations.md, story.md, terminology.md deliberately absent.

        data = described_class.load_reference_files(novel_dir)

        expect(data[:novel_info]).to eq("novel info content")
        expect(data[:characters]).to eq("characters content")
        expect(data[:translation_guidelines]).to eq("")
        expect(data[:voice_calibration]).to eq("")
        expect(data[:cultural_phrases]).to eq("")
        expect(data[:locations]).to eq("")
        expect(data[:story]).to eq("")
        expect(data[:terminology]).to eq("")
      end
    end
  end
end
