require "rails_helper"

# system_prompt_sample.txt was generated by invoking the real Python
# build_translation_prompt directly and saving its output, then hand-
# stripping the one deliberate difference (the web_search-instructing
# sentence — see the class comment) — not hand-transcribed, so this asserts
# genuine byte-for-byte parity per docs/RAILS_REFACTOR_PLAN.md's R4
# acceptance criterion, modulo that one named difference.
RSpec.describe Pipeline::Ruby::TranslateBatch::PromptBuilder do
  def fixture(name)
    File.read(Rails.root.join("spec/fixtures/translate_batch", name), encoding: "UTF-8")
  end

  describe ".build_system_prompt" do
    it "byte-matches Python's build_translation_prompt output, minus the deliberately stripped web_search sentence" do
      context = described_class::TranslationContext.new(
        novel_info: "Genre: romance fantasy\nSetting: modern Seoul idol industry",
        translation_guidelines: "Phase 1: literal pass. Phase 2: polish for readability.",
        narrator_note: "Kang narrates in first person, dry and self-deprecating.",
        characters: "## Hyuk Kang — English\n- Role: protagonist",
        cultural_phrases: "[Phrase — English or descriptive label]\n- Korean phrase: ",
        locations: "## K Management — English\n- Significance: protagonist's new agency",
        story: "",
        terminology: "## Comeback — English\n- Definition: a group's return with new material",
        voice_calibration: "## Passage 1 — Dry deflection\n> quote here"
      )

      expect(described_class.build_system_prompt(context)).to eq(fixture("system_prompt_sample.txt"))
    end

    it "never emits the web_search sentence — R3's bridge doesn't wire that tool" do
      context = described_class::TranslationContext.new(
        novel_info: "info", translation_guidelines: "", narrator_note: "",
        characters: "", cultural_phrases: "", locations: "", story: "",
        terminology: "", voice_calibration: ""
      )

      expect(described_class.build_system_prompt(context)).not_to include("web_search")
    end

    it "omits reference sections that are empty or template-only, same as Python's section() filter" do
      context = described_class::TranslationContext.new(
        novel_info: "", translation_guidelines: "", narrator_note: "",
        characters: "", cultural_phrases: "", locations: "", story: "",
        terminology: "", voice_calibration: ""
      )

      message = described_class.build_system_prompt(context)
      expect(message).not_to include("Character Bible")
      expect(message).not_to include("Narrator Note")
    end
  end

  describe ".build_structured_system_prompt" do
    def context(overrides = {})
      described_class::TranslationContext.new(
        **{
          novel_info: "Genre: romance fantasy", translation_guidelines: "Be faithful.",
          narrator_note: "Kang narrates dryly.", characters: "## Hyuk Kang\n- Role: protagonist",
          cultural_phrases: "", locations: "", story: "", terminology: "", voice_calibration: ""
        }.merge(overrides)
      )
    end

    it "instructs the model to return a single JSON object with intent, literal, and localized keys" do
      prompt = described_class.build_structured_system_prompt(context)

      expect(prompt).to include('"intent"')
      expect(prompt).to include('"literal_translation"')
      expect(prompt).to include('"localized_translation"')
      expect(prompt).to include("Respond with a single JSON object")
    end

    it "includes the same reference material as the single-pass prompt" do
      structured = described_class.build_structured_system_prompt(context)
      single_pass = described_class.build_system_prompt(context)

      expect(structured).to include("Genre: romance fantasy")
      expect(structured).to include("Hyuk Kang")
      # Both prompts should agree on which reference sections were non-empty.
      expect(structured).to include("Character Bible")
      expect(single_pass).to include("Character Bible")
    end

    it "omits reference sections that are empty or template-only, same as the single-pass prompt" do
      prompt = described_class.build_structured_system_prompt(context(characters: "", novel_info: ""))

      expect(prompt).not_to include("Character Bible")
    end

    it "never emits the web_search sentence" do
      expect(described_class.build_structured_system_prompt(context)).not_to include("web_search")
    end

    it "instructs that per-sentence naturalness wins over cross-chapter motif consistency" do
      prompt = described_class.build_structured_system_prompt(context)

      expect(prompt).to include("if repeating it makes one of those sentences read unnaturally on its own, rephrase that sentence")
    end

    it "includes cultural_dynamic and localization_strategy in the intent schema" do
      prompt = described_class.build_structured_system_prompt(context)

      expect(prompt).to include('"cultural_dynamic"')
      expect(prompt).to include('"localization_strategy"')
    end

    it "instructs localized_translation to carry out the stated localization_strategy" do
      prompt = described_class.build_structured_system_prompt(context)

      expect(prompt).to include("localized_translation must carry out its stated localization_strategy")
    end

    it "injects cultural_patterns content into its own section, separate from the shared reference material" do
      prompt = described_class.build_structured_system_prompt(context, cultural_patterns: "Status-jockeying (기 싸움) notes here")

      expect(prompt).to include("## Cultural Patterns")
      expect(prompt).to include("Status-jockeying (기 싸움) notes here")
    end

    it "omits the Cultural Patterns section heading when no cultural_patterns content is given" do
      prompt = described_class.build_structured_system_prompt(context)

      expect(prompt).not_to include("## Cultural Patterns")
    end

    it "never leaks cultural_patterns content into the single-pass prompt" do
      described_class.build_structured_system_prompt(context, cultural_patterns: "some pattern notes")
      single_pass = described_class.build_system_prompt(context)

      expect(single_pass).not_to include("some pattern notes")
    end
  end

  describe ".build_call1_system_prompt" do
    def context(overrides = {})
      described_class::TranslationContext.new(
        **{
          novel_info: "Genre: romance fantasy", translation_guidelines: "Be faithful.",
          narrator_note: "Kang narrates dryly.", characters: "## Hyuk Kang\n- Role: protagonist",
          cultural_phrases: "", locations: "", story: "", terminology: "", voice_calibration: ""
        }.merge(overrides)
      )
    end

    it "instructs the model to return a single JSON object with a passages array and chapter_level_notes" do
      prompt = described_class.build_call1_system_prompt(context)

      expect(prompt).to include('"passages"')
      expect(prompt).to include('"chapter_level_notes"')
      expect(prompt).to include("Respond with a single JSON object")
    end

    it "requires segmentation to be an exhaustive, ordered, non-overlapping partition of the whole chapter" do
      prompt = described_class.build_call1_system_prompt(context)

      expect(prompt).to include("exhaustive")
      expect(prompt).to include("non-overlapping")
      expect(prompt).to include("not just notable")
    end

    it "specifies passage_id as the join key and anchor_quote as verbatim source text" do
      prompt = described_class.build_call1_system_prompt(context)

      expect(prompt).to include('"passage_id"')
      expect(prompt).to include('"anchor_quote"')
      expect(prompt).to include("verbatim")
    end

    it "includes the per-passage analysis fields" do
      prompt = described_class.build_call1_system_prompt(context)

      expect(prompt).to include('"literal_meaning"')
      expect(prompt).to include('"cultural_signals"')
      expect(prompt).to include('"narrative_intent"')
      expect(prompt).to include('"localization_strategy"')
      expect(prompt).to include('"bible_entries_used"')
    end

    it "constrains localization_strategy.category to the controlled six-value taxonomy plus none" do
      prompt = described_class.build_call1_system_prompt(context)

      %w[behavioral idiomatic tone_shift register_shift motif_reinterpretation demographic_voice none].each do |value|
        expect(prompt).to include(value)
      end
    end

    it "scopes bible_entries_used to attribution only, not a content dump" do
      prompt = described_class.build_call1_system_prompt(context)

      expect(prompt).to include("bible_lookup")
    end

    it "instructs chapter_level_notes.risks to record suspected gaps instead of guessing silently" do
      prompt = described_class.build_call1_system_prompt(context)

      expect(prompt).to include('"risks"')
      expect(prompt.downcase).to include("guess")
    end

    it "never emits the web_search sentence" do
      expect(described_class.build_call1_system_prompt(context)).not_to include("web_search")
    end

    it "does not instruct translation — this call is analysis only" do
      prompt = described_class.build_call1_system_prompt(context)

      expect(prompt).not_to include("localized_translation")
      expect(prompt).not_to include("literal_translation")
    end

    it "includes the same reference material as the single-pass prompt" do
      call1 = described_class.build_call1_system_prompt(context)

      expect(call1).to include("Genre: romance fantasy")
      expect(call1).to include("Hyuk Kang")
      expect(call1).to include("Character Bible")
    end

    it "omits reference sections that are empty or template-only" do
      prompt = described_class.build_call1_system_prompt(context(characters: "", novel_info: ""))

      expect(prompt).not_to include("Character Bible")
    end

    it "injects cultural_patterns content into its own section, separate from the shared reference material" do
      prompt = described_class.build_call1_system_prompt(context, cultural_patterns: "Status-jockeying (기 싸움) notes here")

      expect(prompt).to include("## Cultural Patterns")
      expect(prompt).to include("Status-jockeying (기 싸움) notes here")
    end

    it "omits the Cultural Patterns section heading when no cultural_patterns content is given" do
      prompt = described_class.build_call1_system_prompt(context)

      expect(prompt).not_to include("## Cultural Patterns")
    end

    it "never leaks cultural_patterns content into the single-pass prompt" do
      described_class.build_call1_system_prompt(context, cultural_patterns: "some pattern notes")
      single_pass = described_class.build_system_prompt(context)

      expect(single_pass).not_to include("some pattern notes")
    end
  end

  describe ".extract_narrator_note" do
    it "extracts the Narrator Note section when followed by another section" do
      novel_info = "# Title\n\n## Narrator Note\nSome note text.\nMore text.\n\n## Next Section\nOther stuff"
      expect(described_class.extract_narrator_note(novel_info)).to eq("Some note text.\nMore text.")
    end

    it "extracts the Narrator Note section when it's the last section in the file" do
      novel_info = "# Title\n\n## Narrator Note\nSome note text.\n"
      expect(described_class.extract_narrator_note(novel_info)).to eq("Some note text.")
    end

    it "returns an empty string when there is no Narrator Note section" do
      expect(described_class.extract_narrator_note("# Title\n\n## Other Section\nstuff")).to eq("")
    end

    it "handles Korean content inside the note without an ASCII-only \\w gap" do
      novel_info = "## Narrator Note\n강혁 narrates dryly.\n\n## Next"
      expect(described_class.extract_narrator_note(novel_info)).to eq("강혁 narrates dryly.")
    end

    it "returns an empty string for nil input" do
      expect(described_class.extract_narrator_note(nil)).to eq("")
    end
  end

  describe ".load_reference_files" do
    it "reads all 8 NOVEL_FILES from the novel/bible directories, empty string for missing ones" do
      Dir.mktmpdir do |novel_dir|
        FileUtils.mkdir_p(File.join(novel_dir, "bible"))
        File.write(File.join(novel_dir, "novel_info.md"), "novel info content")
        File.write(File.join(novel_dir, "bible", "characters.md"), "characters content")
        # translation_guidelines.md, voice_calibration.md, cultural_phrases.md,
        # locations.md, story.md, terminology.md deliberately absent.

        data = described_class.load_reference_files(novel_dir)

        expect(data[:novel_info]).to eq("novel info content")
        expect(data[:characters]).to eq("characters content")
        expect(data[:translation_guidelines]).to eq("")
        expect(data[:voice_calibration]).to eq("")
        expect(data[:cultural_phrases]).to eq("")
        expect(data[:locations]).to eq("")
        expect(data[:story]).to eq("")
        expect(data[:terminology]).to eq("")
      end
    end
  end
end
