require "rails_helper"

# Fixtures under spec/fixtures/post_translation_review/ were generated by
# invoking the real Python functions (src/bible_review/prompt_builder.py)
# directly and saving their output — not hand-transcribed — so these assert
# genuine byte-for-byte parity per docs/RAILS_REFACTOR_PLAN.md's R5
# acceptance criterion, not just a plausible-looking approximation.
RSpec.describe Pipeline::Ruby::PostTranslationReview::PromptBuilder do
  def fixture(name)
    File.read(Rails.root.join("spec/fixtures/post_translation_review", name), encoding: "UTF-8")
  end

  describe ".build_system_prompt" do
    it "byte-matches Python's build_system_prompt output for the same date and chapter" do
      expect(described_class.build_system_prompt("2026-07-25", 5))
        .to eq(fixture("system_prompt_2026-07-25_ch5.txt"))
    end
  end

  describe ".build_user_message" do
    it "byte-matches Python's build_user_message output for the same context" do
      context = described_class::ReviewContext.new(
        novel_info:         "A story about an idol group's comeback.",
        characters:         "## Kim Min-jun (김민준) — English\n- Korean name: 김민준\n- Role: protagonist\n",
        cultural_phrases:   "",
        locations:          "[Location Name — English]\n- Korean name: \n",
        story:              "Current summary: \n- Key turning points:\n",
        terminology:        "",
        translated_chapter: "The rain fell steadily over Seoul as Min-jun walked home.\nHe thought about the audition.\n",
        chapter_num:        5,
        today:              "2026-07-25"
      )

      expect(described_class.build_user_message(context)).to eq(fixture("user_message_sample.txt"))
    end

    it "omits reference sections that are empty or template-only, same as Python's section() filter" do
      context = described_class::ReviewContext.new(
        novel_info: "", characters: "", cultural_phrases: "", locations: "",
        story: "", terminology: "", translated_chapter: "text", chapter_num: 1, today: "2026-07-25"
      )

      message = described_class.build_user_message(context)
      expect(message).not_to include("Current Characters Bible")
      expect(message).to include("# Translated Chapter 1")
    end
  end
end
